### ISSUE TITLE
Ceh /disabler doesn't disable recipes properly

### ISSUE THREAD

**Issue by Titeiiko** [DutchJelly/CraftEnhance#36] opened 2021-06-18 19:35 UTC
**Describe the bug**
I am aware that there is another issue similar to this but wanna apply more information.
/ceh disabler works like it does disable recipes **BUT** it doesn't save it. Meaning if I reload the server then nothing works. **in addition,** the config doesn't update as well and it also weirdly breaks the gui. 

**To Reproduce**
1. /ceh disable
2. Disable anything. (Config doesn't update)
3. /ceh reload
4. Go back to /ceh disable and now for some reason you no longer have ability to disable any recipe. The only thing you can access / adjust is the recipes you **already disabled.**

**Show console logs**
![image](https://user-images.githubusercontent.com/65754609/122608633-6916aa00-d031-11eb-8a6f-cb5b08870cca.png)

**Other Info, using Plugman reload**
If you use the plugman plugin (plugin useful for reloading plugins more successfully and better) then it gives a much much bigger error.
![image](https://user-images.githubusercontent.com/65754609/122608756-a2e7b080-d031-11eb-85e6-9a68df456a37.png)

**Comment by DutchJelly** [comment] 2021-07-23 12:51
Thank you for reporting this. The bug is caused by the command `/ceh reload` not working properly.

This is fixed in version 2.4.3 (which is currently in beta testing).

**Closed by DutchJelly** 2021-07-23 12:51 UTC
Labels: bug
